// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtwkqxnsabqadrrxpdwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10d2txeG5zYWJxYWRycnhwZHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzY0MzMsImV4cCI6MjA2NTIxMjQzM30.swx6IDxpK1hNZoWSrAP6N3-sabStSp6Jeh0sy4U4a28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);